[package]
name = "datafusion-randgen-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }
arrow-array = { version = "59.3.0", default-features = false }
arrow-schema = { version = "59.3.0", default-features = false }
datafusion = { version = "55.0.0", default-features = false, features = ["sql", "nested_expressions"] }
datafusion-common = { version = "55.0.0", default-features = false }
datafusion-expr = { version = "55.0.0", default-features = false }
datafusion-randgen = { path = "..", features = ["column-choice-arrow-ipc", "column-choice-parquet"] }
datafusion-roaring = "0.1.0"
libfuzzer-sys = "0.4.13"
roaring = "0.11.5"
tokio = { version = "1.53.1", features = ["full"] }

[[bin]]
name = "direct_api"
path = "fuzz_targets/direct_api.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sql_api"
path = "fuzz_targets/sql_api.rs"
test = false
doc = false
bench = false
